name: data-analysis-labeling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  - matplotlib>=3.5.0
  - plotly>=5.0.0
  - h5py>=3.7.0
  - pyarrow>=10.0.0
  - scikit-learn>=1.1.0
  - pip
  - pip:
    - dash>=2.6.0
    - dash-bootstrap-components>=1.4.0
    - streamlit>=1.25.0
    - PyWavelets>=1.4.0
